### ISSUE TITLE
Namespace choice

### ISSUE THREAD

**Issue by kraih** [sjdy521/Mojo-IRC-Server#3]
It is a little unfortunate that you've chosen the generic namespace `Mojo::IRC::Server` for a language specific module, this conflicts with `Mojo::IRC` and is bound to confuse other Mojolicious users in the future. I believe that a more descriptive namespace like `Mojo::IRC::Server::Chinese` or even `Chinese::IRC::Server` would have been a much better choice here.

**Comment by zoffixznet** [comment]
:+1: 

@sjdy521 would you be open to transfering to an alternate, more specific namespace (e.g. `Mojo::IRC::Server::Chinese`) and releasing the `Mojo::IRC::Server` namespace for use by a more generic package? If you need any help with the process, feel free to ask.

**Comment by hexsum** [comment]
The suggestion is reasonable.
Although I prefer to use `Mojo::IRC::Server`, but this module doesn't implement full-feature and standard IRC protocol. so I will change it to `Mojo::IRC::Server::Chinese` 

By the way, I am very curious why major contributors of mojo project get interested in this namespace because this module has been released to cpan for a while
Do you guys plan to provide some thing like a IRC Server by mojo?

**Comment by kraih** [comment]
No plans, we have an IRC bot in `#mojo` that announces recent CPAN uploads, your module popped up earlier today and started a little discussion. :smiley:

**Comment by jberger** [comment]
I would love to see a full featured Mojo::IRC::Server, perhaps yours can be a starting point?

**Comment by hexsum** [comment]
@kraih  @zoffixznet  
Mojo::IRC::Server -> Mojo::IRC::Server::Chinese, it's done

@jberger 
I create this module because I can not find out any IRC Server supporting Chinese nickname.
my implementation is not well-designed,  it's only for my own use most of the time.
it may not be a good starting point;

Actually you can find out many open-source mature IRC project, for example: `ngIRCd` `ircd-ircu` `ircd-hybrid`
but I am really looking forward to  see a full-featured irc server written in Perl too.

**Comment by zoffixznet** [comment]
Awesome! Thanks a lot
